# Navigation Links

main:
  - name: Home
    url: /
    weight: 10
  - name: Publications
    url: /publications/
    weight: 20
  - name: Projects
    url: /projects/
    weight: 30
  - name: Notes
    url: /notes/
    weight: 40
  - name: CV
    url: /cv/
    weight: 50
